### ISSUE TITLE
Typo syllabus 

### ISSUE THREAD

**Issue by GautierG** [UCL-INMA/LINMA2345#38]
Je pense avoir trouvé quelques rectifications dans le syllabus (A vérifier) :

- [x] P46 Au début x is the probability to play Rr et pas Rf
- [x] P57 Example 28, the card game of example 23 (or 7) is given by et pas 28
- [x] P64 the strategic form en haut de la page, ce n'est pas plutôt -1,2 à la place de -2,2 pour le stratégie (Sr,Nh)
- [ ] P69 Au début, quand il est mis However, only the second one is subgame perfect, ce n'est pas plutôt the first one c'est à dire (x1,x2).
- [x] P74 à la fin il est mis qu'il y a 3 équilibres de Nash, ok mais le 3ème n'est pas (0.5G+0.5W,0.5g+0.5w) je pense, j'ai trouvé (3/13G + 10/13W,3/13g + 10/13w)

**Comment by blegat** [comment]
The typo P46 has been fixed by #48

**Comment by gauthmug** [comment]
The typo on page 57 has been fixed in https://github.com/UCL-INMA/LINMA2345/pull/53/commits/4a66b43c454832be94348114dd476ab0ddea2203.
The typo on page 64 has been fixed in https://github.com/UCL-INMA/LINMA2345/pull/60/commits/7172ed3b9f0422d4aa37c41cb96f6bc6634a3f68.
The typo on page 74 has been fixed in https://github.com/UCL-INMA/LINMA2345/pull/60/commits/1de16ae7510e8cf5d3c86112c7d74b5d9326582a.
